// Centralized locale strings and object descriptions.
export const LANGUAGE_CODES = ['fi', 'en', 'sv', 'de', 'el'];

export const LOCALES = {
  fi: {
    nativeName: 'Suomi',
    flag: '🇫🇮',
    numberFormat: 'fi-FI',
    title: 'Aurinkokuntasimulaatio',
    hints: {
      controls: 'Marko Grönroos, 2025',
      time: '',
    },
    stats: {
      time: 'Simulaation aika (UTC)',
      speed: 'Nopeuskerroin',
      realTime: '1x (reaaliaika)',
    },
    instructionsTitle: 'Ohje',
    instructions: [
      'Napsauta kohdetta valitaksesi; tuplaklikkaa lukitaksesi kameran.',
      'Pyöritä näkymää hiiren painikkeella, zoomaa rullalla ja siirrä näkymää vetämällä oikealla painikkeella, kun seuranta on pois päältä.',
      'Planeettojen koot on korostettu näkyvyyden parantamiseksi.',
    ],
    buttons: {
      lock: 'Lukitse seuranta',
      following: 'Seuranta päällä',
      unlock: 'Vapauta',
      now: 'NYT',
      play: 'Käynnistä simulointi',
      pause: 'Pysäytä simulointi',
    },
    selection: {
      title: 'Valittu kohde',
      none: 'Ei valittua kohdetta.',
      meanDistance: 'Keski-etäisyys',
      diameter: 'Halkaisija',
      rotation: 'Pyörähdysaika',
      cameraLocked: 'Kamera lukittu tähän kohteeseen.',
    },
    typeNames: {
      star: 'tähti',
      planet: 'planeetta',
      moon: 'kuu',
      'dwarf-planet': 'kääpiöplaneetta',
    },
    units: {
      hour: 'h',
      day: 'vrk',
    },
    ariaLanguageButton: 'Valitse kieli',
  },
  en: {
    nativeName: 'English',
    flag: '🇬🇧',
    numberFormat: 'en-US',
    title: 'Solar System Simulation',
    hints: {
      controls: 'Marko Grönroos, 2025',
      time: '',
    },
    stats: {
      time: 'Simulation time (UTC)',
      speed: 'Speed factor',
      realTime: '1x (real time)',
    },
    instructionsTitle: 'Guide',
    instructions: [
      'Click an object to select it; double-click to lock the camera.',
      'Drag to rotate, zoom with the scroll wheel, and pan by dragging with the right mouse button when tracking is off.',
      'Planet sizes are exaggerated for clarity.',
    ],
    buttons: {
      lock: 'Lock tracking',
      following: 'Tracking active',
      unlock: 'Release',
      now: 'NOW',
      play: 'Start simulation',
      pause: 'Pause simulation',
    },
    selection: {
      title: 'Selected object',
      none: 'No object selected.',
      meanDistance: 'Mean distance',
      diameter: 'Diameter',
      rotation: 'Rotation period',
      cameraLocked: 'Camera locked to this object.',
    },
    typeNames: {
      star: 'star',
      planet: 'planet',
      moon: 'moon',
      'dwarf-planet': 'dwarf planet',
    },
    units: {
      hour: 'h',
      day: 'd',
    },
    ariaLanguageButton: 'Select language',
  },
  sv: {
    nativeName: 'Svenska',
    flag: '🇸🇪',
    numberFormat: 'sv-SE',
    title: 'Solsystemets simulering',
    hints: {
      controls: 'Marko Grönroos, 2025',
      time: '',
    },
    stats: {
      time: 'Simulerad tid (UTC)',
      speed: 'Hastighetsfaktor',
      realTime: '1x (realtid)',
    },
    instructionsTitle: 'Guide',
    instructions: [
      'Klicka på ett objekt för att välja det; dubbelklick låser kameran.',
      'Dra för att rotera, zooma med rullhjulet och panorera genom att dra med höger musknapp när följningen är av.',
      'Planeternas storlek är överdriven för tydlighet.',
    ],
    buttons: {
      lock: 'Lås följning',
      following: 'Följning på',
      unlock: 'Frigör',
      now: 'NU',
      play: 'Starta simulering',
      pause: 'Pausa simulering',
    },
    selection: {
      title: 'Valt objekt',
      none: 'Inget objekt valt.',
      meanDistance: 'Medelavstånd',
      diameter: 'Diameter',
      rotation: 'Rotationstid',
      cameraLocked: 'Kameran är låst till objektet.',
    },
    typeNames: {
      star: 'stjärna',
      planet: 'planet',
      moon: 'måne',
      'dwarf-planet': 'dvärgplanet',
    },
    units: {
      hour: 'h',
      day: 'dygn',
    },
    ariaLanguageButton: 'Välj språk',
  },
  de: {
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    numberFormat: 'de-DE',
    title: 'Simulation des Sonnensystems',
    hints: {
      controls: 'Marko Grönroos, 2025',
      time: '',
    },
    stats: {
      time: 'Simulationszeit (UTC)',
      speed: 'Geschwindigkeitsfaktor',
      realTime: '1x (Echtzeit)',
    },
    instructionsTitle: 'Anleitung',
    instructions: [
      'Klicken Sie ein Objekt an, um es zu wählen; Doppelklick fixiert die Kamera.',
      'Ziehen Sie zum Drehen, zoomen Sie mit dem Scrollrad und verschieben Sie durch Ziehen mit der rechten Maustaste, wenn keine Verfolgung aktiv ist.',
      'Planeten sind zur besseren Lesbarkeit vergrößert dargestellt.',
    ],
    buttons: {
      lock: 'Verfolgung sperren',
      following: 'Verfolgung aktiv',
      unlock: 'Freigeben',
      now: 'JETZT',
      play: 'Simulation starten',
      pause: 'Simulation pausieren',
    },
    selection: {
      title: 'Ausgewähltes Objekt',
      none: 'Kein Objekt ausgewählt.',
      meanDistance: 'Mittlere Entfernung',
      diameter: 'Durchmesser',
      rotation: 'Rotationsperiode',
      cameraLocked: 'Kamera auf dieses Objekt fixiert.',
    },
    typeNames: {
      star: 'Stern',
      planet: 'Planet',
      moon: 'Mond',
      'dwarf-planet': 'Zwergplanet',
    },
    units: {
      hour: 'h',
      day: 'Tage',
    },
    ariaLanguageButton: 'Sprache wählen',
  },
  el: {
    nativeName: 'Ελληνικά',
    flag: '🇬🇷',
    numberFormat: 'el-GR',
    title: 'Προσομοίωση Ηλιακού Συστήματος',
    hints: {
      controls: 'Marko Grönroos, 2025',
      time: '',
    },
    stats: {
      time: 'Χρόνος προσομοίωσης (UTC)',
      speed: 'Συντελεστής ταχύτητας',
      realTime: '1x (πραγματικός χρόνος)',
    },
    instructionsTitle: 'Οδηγίες',
    instructions: [
      'Επιλέξτε σώμα με κλικ· διπλό κλικ κλειδώνει την κάμερα.',
      'Σύρετε για περιστροφή, ζουμάρετε με τη ροδέλα και μετατοπίστε σύροντας με το δεξί κουμπί του ποντικιού όταν η παρακολούθηση είναι ανενεργή.',
      'Τα μεγέθη των πλανητών είναι υπερμεγεθυσμένα για ευκρίνεια.',
    ],
    buttons: {
      lock: 'Κλείδωμα παρακολούθησης',
      following: 'Η παρακολούθηση ενεργή',
      unlock: 'Απελευθέρωση',
      now: 'ΤΩΡΑ',
      play: 'Έναρξη προσομοίωσης',
      pause: 'Παύση προσομοίωσης',
    },
    selection: {
      title: 'Επιλεγμένο σώμα',
      none: 'Δεν έχει επιλεγεί σώμα.',
      meanDistance: 'Μέση απόσταση',
      diameter: 'Διάμετρος',
      rotation: 'Περίοδος περιστροφής',
      cameraLocked: 'Η κάμερα είναι κλειδωμένη σε αυτό το σώμα.',
    },
    typeNames: {
      star: 'άστρο',
      planet: 'πλανήτης',
      moon: 'δορυφόρος',
      'dwarf-planet': 'νάνος πλανήτης',
    },
    units: {
      hour: 'ώ',
      day: 'ημ.',
    },
    ariaLanguageButton: 'Επιλογή γλώσσας',
  },
};

export const DESCRIPTIONS = {
  sun: {
    fi: 'Järjestelmän keskuskappale, joka valaisee ja vetää puoleensa kaikki muut kohteet.',
    en: 'Central star providing light and gravity for the system.',
    sv: 'Den centrala stjärnan som ger systemet ljus och gravitation.',
    de: 'Der zentrale Stern, der dem System Licht und Schwerkraft liefert.',
    el: 'Το κεντρικό άστρο που παρέχει φως και βαρύτητα στο σύστημα.',
  },
  mercury: {
    fi: 'Sisimmäinen planeetta, jonka hitaasti pyörivä pinta paahtuu Auringon lähellä.',
    en: 'Innermost planet whose slowly rotating surface bakes close to the Sun.',
    sv: 'Den innersta planeten vars långsamt roterande yta hettas upp nära solen.',
    de: 'Der innerste Planet, dessen langsam rotierende Oberfläche in Sonnennähe erhitzt wird.',
    el: 'Ο πιο εσωτερικός πλανήτης με αργά περιστρεφόμενη επιφάνεια που καίγεται κοντά στον Ήλιο.',
  },
  venus: {
    fi: 'Paksuun pilvikerrokseen kääritty planeetta, joka pyörii taaksepäin.',
    en: 'Cloud-wrapped planet that rotates backwards.',
    sv: 'En molntäckt planet som roterar baklänges.',
    de: 'Ein von Wolken verhüllter Planet, der rückwärts rotiert.',
    el: 'Ένας πλανήτης σκεπασμένος από σύννεφα που περιστρέφεται ανάποδα.',
  },
  earth: {
    fi: 'Kotiplaneetta, jonka meri ja maanosat näkyvät tekstuurissa.',
    en: 'Our home planet with oceans and continents visible on the map.',
    sv: 'Vår hemplanet där hav och kontinenter syns på kartan.',
    de: 'Unser Heimatplanet, dessen Ozeane und Kontinente auf der Karte sichtbar sind.',
    el: 'Ο πλανήτης μας, με ωκεανούς και ηπείρους ορατούς στον χάρτη.',
  },
  moon: {
    fi: 'Maan kuu, joka hallitsee vuorovesiä ja pyörähtää kerran kiertonsa aikana.',
    en: 'Earth’s moon, driving the tides and rotating once per orbit.',
    sv: 'Jordens måne som styr tidvattnet och roterar ett varv per omlopp.',
    de: 'Der Mond der Erde, der die Gezeiten lenkt und sich einmal pro Umlauf dreht.',
    el: 'Η Σελήνη της Γης, που ρυθμίζει τις παλίρροιες και περιστρέφεται μία φορά ανά τροχιά.',
  },
  mars: {
    fi: 'Punainen planeetta, jossa on jäiset navat ja pölymyrskyjä.',
    en: 'The red planet with icy poles and frequent dust storms.',
    sv: 'Den röda planeten med isiga poler och återkommande dammstormar.',
    de: 'Der rote Planet mit eisigen Polkappen und häufigen Staubstürmen.',
    el: 'Ο κόκκινος πλανήτης με παγωμένους πόλους και συχνές καταιγίδες σκόνης.',
  },
  phobos: {
    fi: 'Marsin sisempi, epäsäännöllinen kuu; kiertoaika alle kahdeksan tuntia.',
    en: 'Innermost Martian moon, irregular and racing around in under eight hours.',
    sv: 'Mars innersta måne, oregelbunden och med en omloppstid under åtta timmar.',
    de: 'Innerster Marsmond, unregelmäßig geformt und in weniger als acht Stunden um den Planeten.',
    el: 'Ο εσωτερικότερος δορυφόρος του Άρη, ακανόνιστος και με περίοδο κάτω από οκτώ ώρες.',
  },
  deimos: {
    fi: 'Marsin ulompi kuu, pienikokoinen ja hitaammin kiertävä kuin Phobos.',
    en: 'Outer Martian moon, small and orbiting more slowly than Phobos.',
    sv: 'Mars yttre måne, liten och långsammare än Phobos.',
    de: 'Äußerer Marsmond, klein und langsamer unterwegs als Phobos.',
    el: 'Ο εξωτερικός δορυφόρος του Άρη, μικρός και πιο αργός από τον Φόβο.',
  },
  jupiter: {
    fi: 'Aurinkokunnan massiivisin planeetta, jonka pilvivöissä näkyy suuri punainen pilkku.',
    en: 'Most massive planet of the system, its cloud bands host the Great Red Spot.',
    sv: 'Systemets mest massiva planet med molnband som hyser den Stora röda fläcken.',
    de: 'Der massereichste Planet des Systems; seine Wolkenbänder tragen den Großen Roten Fleck.',
    el: 'Ο πιο ογκώδης πλανήτης του συστήματος, με ζώνες νεφών και τη Μεγάλη Ερυθρά Κηλίδα.',
  },
  io: {
    fi: 'Tuliperäinen kuu, jonka pinnalla purkautuu lukuisia laavoja.',
    en: 'Volcanic moon covered in active lava eruptions.',
    sv: 'En vulkanisk måne täckt av aktiva lavautbrott.',
    de: 'Ein vulkanischer Mond, bedeckt von aktiven Lavaaustritten.',
    el: 'Δορυφόρος με έντονη ηφαιστειακή δραστηριότητα και συνεχή εκρήξεις λάβας.',
  },
  europa: {
    fi: 'Jääkuoren alla saattaa olla suolainen valtameri.',
    en: 'May hide a salty ocean beneath its ice shell.',
    sv: 'Kan dölja ett salt hav under sitt istäcke.',
    de: 'Könnte unter seiner Eisdecke einen salzigen Ozean verbergen.',
    el: 'Ίσως κρύβει έναν αλμυρό ωκεανό κάτω από το κέλυφος πάγου.',
  },
  ganymede: {
    fi: 'Aurinkokunnan suurin kuu, suurempi kuin Merkurius.',
    en: 'Largest moon in the solar system, bigger than Mercury.',
    sv: 'Det största månen i solsystemet, större än Merkurius.',
    de: 'Der größte Mond des Sonnensystems, größer als Merkur.',
    el: 'Ο μεγαλύτερος δορυφόρος του ηλιακού συστήματος, μεγαλύτερος από τον Ερμή.',
  },
  callisto: {
    fi: 'Vanha ja kraatteroitunut kuu Jupiterin ulkokehällä.',
    en: 'Old, heavily cratered moon on Jupiter’s outer track.',
    sv: 'En gammal, kraftigt kraterfylld måne i Jupiters yttre bana.',
    de: 'Ein alter, stark verkraterter Mond auf Jupiters äußerer Bahn.',
    el: 'Παλιός δορυφόρος με πολλούς κρατήρες στη εξωτερική τροχιά του Δία.',
  },
  saturn: {
    fi: 'Kaasujätti, jonka ikoniset renkaat hallitsevat näkymää.',
    en: 'Gas giant whose iconic rings dominate the view.',
    sv: 'Gasutjätte vars ikoniska ringar dominerar vyn.',
    de: 'Gasriese, dessen ikonische Ringe das Erscheinungsbild bestimmen.',
    el: 'Γίγαντας αερίων με εμβληματικούς δακτυλίους που κυριαρχούν στην εικόνα.',
  },
  mimas: {
    fi: 'Pieni ja voimakkaasti kraatteroitu Saturnuksen kuu.',
    en: 'Small, heavily cratered moon of Saturn.',
    sv: 'En liten, hårt kratermärkt Saturnusmåne.',
    de: 'Kleiner, stark verkraterter Saturnmond.',
    el: 'Μικρός δορυφόρος του Κρόνου γεμάτος κρατήρες.',
  },
  enceladus: {
    fi: 'Jääinen kuu, jonka etelänavasta purkautuu vesihöyryä.',
    en: 'Icy moon venting water vapour from its south pole.',
    sv: 'Isig måne som sprutar ut vattenånga från sydpolen.',
    de: 'Eisiger Mond, der Wasserdampf aus seiner Südpolregion ausstößt.',
    el: 'Παγωμένος δορυφόρος που εκτινάσσει υδρατμούς από τον νότιο πόλο.',
  },
  tethys: {
    fi: 'Saturnuksen kuu, jonka rata on lähes täydellisen ympyrä.',
    en: 'Saturnian moon moving on an almost circular orbit.',
    sv: 'Saturnusmåne med nästan perfekt cirkulär bana.',
    de: 'Saturnmond mit nahezu kreisförmiger Umlaufbahn.',
    el: 'Δορυφόρος του Κρόνου με σχεδόν κυκλική τροχιά.',
  },
  dione: {
    fi: 'Kuu, jonka jäinen pinta on halki rotkoista.',
    en: 'Moon with an icy surface scarred by chasms.',
    sv: 'Måne med isig yta fylld av klyftor.',
    de: 'Mond mit vereister Oberfläche, durchzogen von Schluchten.',
    el: 'Δορυφόρος με παγωμένη επιφάνεια γεμάτη χαράδρες.',
  },
  rhea: {
    fi: 'Saturnuksen toiseksi suurin kuu, hiljaisen kraatterinen.',
    en: 'Saturn’s second-largest moon, quietly cratered.',
    sv: 'Saturnus näst största måne, stilla och kraterfylld.',
    de: 'Zweitgrößter Saturnmond mit zahlreichen, ruhigen Kratern.',
    el: 'Ο δεύτερος μεγαλύτερος δορυφόρος του Κρόνου με ήρεμες περιοχές κρατήρων.',
  },
  titan: {
    fi: 'Paksuun typpiatmosfääriin verhoutunut jättikuu.',
    en: 'Giant moon cloaked in a dense nitrogen atmosphere.',
    sv: 'En jättemåne täckt av en tät kväveatmosfär.',
    de: 'Gigantischer Mond in eine dichte Stickstoffatmosphäre gehüllt.',
    el: 'Γιγάντιος δορυφόρος σκεπασμένος από πυκνή ατμόσφαιρα αζώτου.',
  },
  iapetus: {
    fi: 'Kauempana kiertävä kuu, jonka etu- ja takapuoli poikkeavat voimakkaasti.',
    en: 'Distant moon with strikingly different leading and trailing hemispheres.',
    sv: 'En avlägsen måne med tydligt olika fram- och baksida.',
    de: 'Entfernter Mond mit stark unterschiedlichen Vorder- und Rückseiten.',
    el: 'Απομακρυσμένος δορυφόρος με εντυπωσιακά διαφορετικά ημισφαίρια.',
  },
  uranus: {
    fi: 'Jättiläinen, joka pyörii lähes kyljellään ja omistaa himmeät renkaat.',
    en: 'Giant planet rotating almost on its side with faint rings.',
    sv: 'Gasutjätte som roterar nästan på sidan och har svaga ringar.',
    de: 'Gasriese, der fast auf der Seite rotiert und schwache Ringe besitzt.',
    el: 'Γίγαντας που περιστρέφεται σχεδόν πλαγιασμένος και έχει αμυδρούς δακτυλίους.',
  },
  miranda: {
    fi: 'Pieni kuu täynnä jyrkkiä rotkoja ja mosaiikkisia tasankoja.',
    en: 'Small moon criss-crossed by cliffs and patchwork plains.',
    sv: 'Liten måne fylld av branta klippor och mosaikartade slätter.',
    de: 'Kleiner Mond mit steilen Klippen und flickenartigen Ebenen.',
    el: 'Μικρός δορυφόρος γεμάτος από απότομα φαράγγια και μωσαϊκά πεδία.',
  },
  ariel: {
    fi: 'Kirkas kuu, jonka jääpinnalla näkyy kaivautuneita kanjoneita.',
    en: 'Bright moon whose icy surface is carved by canyons.',
    sv: 'Ljusstark måne vars isiga yta är uppsprucken av kanjoner.',
    de: 'Heller Mond mit eisiger Oberfläche, durchzogen von Canyons.',
    el: 'Φωτεινός δορυφόρος με παγωμένη επιφάνεια γεμάτη φαράγγια.',
  },
  umbriel: {
    fi: 'Tumma kuu, joka kiertää Uranuksen ekvaattoritasossa.',
    en: 'Dark moon orbiting in Uranus’s equatorial plane.',
    sv: 'Mörk måne som går i Uranus ekvatorialplan.',
    de: 'Dunkler Mond in der Äquatorebene des Uranus.',
    el: 'Σκοτεινός δορυφόρος που κινείται στο ισημερινό επίπεδο του Ουρανού.',
  },
  titania: {
    fi: 'Uranuksen suurin kuu, jonka pinnalla näkyy laajoja jäänlaaksoja.',
    en: 'Largest moon of Uranus, showing broad icy valleys.',
    sv: 'Uranus största måne med vidsträckta isdalar.',
    de: 'Größter Mond des Uranus mit ausgedehnten Eis-Tälern.',
    el: 'Ο μεγαλύτερος δορυφόρος του Ουρανού με εκτεταμένες παγωμένες κοιλάδες.',
  },
  oberon: {
    fi: 'Uloin suuri Uranuksen kuu, tumma ja kraatteroitu.',
    en: 'Outermost large Uranian moon, dark and cratered.',
    sv: 'Den yttersta av Uranus stora månar, mörk och kraterfylld.',
    de: 'Äußerster großer Uranusmond, dunkel und verkratert.',
    el: 'Ο πιο εξωτερικός μεγάλος δορυφόρος του Ουρανού, σκοτεινός και γεμάτος κρατήρες.',
  },
  neptune: {
    fi: 'Kaukaisin jättiläinen, jonka myrskyiset ilmavirtaukset ovat äärimmäisiä.',
    en: 'Outermost giant whose storms drive extreme winds.',
    sv: 'Den yttersta jätten vars stormar driver extrema vindar.',
    de: 'Äußerster Riese, dessen Stürme extrem starke Winde erzeugen.',
    el: 'Ο πιο απομακρυσμένος γίγαντας με καταιγίδες που δημιουργούν ακραίους ανέμους.',
  },
  triton: {
    fi: 'Suuri kuu, joka kiertää Neptunusta vastakkaiseen suuntaan ja suihkuttaa typpeä.',
    en: 'Large moon orbiting Neptune backwards and venting nitrogen geysers.',
    sv: 'Stor måne som går runt Neptunus baklänges och sprutar kvävegejsrar.',
    de: 'Großer Mond, der Neptun retrograd umkreist und Stickstoff-Geysire ausstößt.',
    el: 'Μεγάλος δορυφόρος που περιφέρεται αντίθετα από την κίνηση του Ποσειδώνα και εκτοξεύει πίδακες αζώτου.',
  },
  proteus: {
    fi: 'Epäsäännöllinen ja tumma Neptunuksen sisäkuu.',
    en: 'Irregular, dark inner moon of Neptune.',
    sv: 'Oregelbunden och mörk innermåne till Neptunus.',
    de: 'Unregelmäßiger, dunkler innerer Mond des Neptun.',
    el: 'Ακανόνιστος, σκοτεινός εσωτερικός δορυφόρος του Ποσειδώνα.',
  },
  ceres: {
    fi: 'Asteroidivyöhykkeen kääpiöplaneetta, jonka pinta on harmaan ja jäisen kirjava.',
    en: 'Dwarf planet in the asteroid belt with a mottled, icy surface.',
    sv: 'Dvärgplanet i asteroidbältet med flammig, isig yta.',
    de: 'Zwergplanet im Asteroidengürtel mit gefleckter, vereister Oberfläche.',
    el: 'Νάνος πλανήτης στη ζώνη των αστεροειδών με κηλιδωμένη, παγωμένη επιφάνεια.',
  },
};
